src/Entity/Program.php
<?php declare(strict_types=1);

namespace App\Entity;

use App\Traits\SlugTrait;
use App\Traits\TimeStampableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProgramRepository")
 * @UniqueEntity("title")
 * @ORM\HasLifecycleCallbacks
 * @Vich\Uploadable
 */
class Program
{
    use SlugTrait;
    use TimeStampableTrait;

    /**
     * @var int
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=75, unique=true)
     * @Assert\NotBlank
     * @Assert\Type("string")
     */
    private $title;

    /**
     * @var string
     * @ORM\Column(type="text")
     */
    private $synopsis;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster;

    /**
     * @Vich\UploadableField(mapping="program_file", fileNameProperty="poster")
     *
     * @var File
     * @Assert\File()
     */
    private $posterFile;

    /**
     * @var Country|null
     * @ORM\ManyToOne(targetEntity=Country::class)
     */
    private $country;

    // TODO max : mettre l'année actuel
    /**
     * @var int|null
     * @ORM\Column(type="smallint", nullable=true)
     * @Assert\Range(
     *      min = 1890,
     *      max = 2500,
     * )
     */
    private $year;

    /**
     * @var Category
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="programs")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull()
     */
    private $category;

    /**
     * @var Season[]|Collection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Season", mappedBy="program", orphanRemoval=true)
     */
    private $seasons;

    /**
     * @var Actor[]|Collection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Actor", mappedBy="programs")
     */
    private $actors;

    public function __construct()
    {
        $this->seasons = new ArrayCollection();
        $this->actors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        $this->setSlug($title);

        return $this;
    }

    public function getSynopsis(): ?string
    {
        return $this->synopsis;
    }

    public function setSynopsis(string $synopsis): self
    {
        $this->synopsis = $synopsis;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(?string $poster): self
    {
        $this->poster = $poster;

        return $this;
    }

    public function getPosterFile(): ?File
    {
        return $this->posterFile;
    }

    public function setPosterFile(File $poster = null): self
    {
        $this->posterFile = $poster;
        if ($poster) {
            $this->updatedAt = new \DateTimeImmutable();
        }

        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(?int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Season[]
     */
    public function getSeasons(): array
    {
        return $this->seasons->toArray();
    }

    public function addSeason(Season $season): self
    {
        if (!$this->seasons->contains($season)) {
            $this->seasons[] = $season;
        }

        return $this;
    }

    public function getNbEpisodes(): int
    {
        return array_reduce($this->getSeasons(), function (int $carry, Season $season) {
            return $carry + \count($season->getEpisodes());
        }, 0);
    }

    public function removeSeason(Season $season): self
    {
        if ($this->seasons->contains($season)) {
            $this->seasons->removeElement($season);
        }

        return $this;
    }

    /**
     * @return Actor[]
     */
    public function getActors(): array
    {
        return $this->actors->toArray();
    }

    public function addActor(Actor $actor): self
    {
        if (!$this->actors->contains($actor)) {
            $this->actors[] = $actor;
            $actor->addProgram($this);
        }

        return $this;
    }

    public function removeActor(Actor $actor): self
    {
        if ($this->actors->contains($actor)) {
            $this->actors->removeElement($actor);
            $actor->removeProgram($this);
        }

        return $this;
    }
}

src/Form/ProgramType.php
<?php declare(strict_types=1);

namespace App\Form;

use App\Entity\Category;
use App\Entity\Country;
use App\Entity\Program;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\PropertyAccess\PropertyPath;
use Vich\UploaderBundle\Form\Type\VichImageType;

class ProgramType extends AbstractType
{
    /**
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'required' => true,
            ])
            ->add(
                'synopsis',
                TextareaType::class,
                [
                    'required' => false,
                ]
            )
            ->add('year', IntegerType::class, [
                'required' => false,
                'attr'     => [
                    'min' => 1890,
                    'max' => 2500,
                ],
            ])
            ->add('country', EntityType::class, [
                'required'     => false,
                'class'        => Country::class,
                'choice_label' => 'name',
                'expanded'     => false,
                'multiple'     => false,
            ])
            ->add('category', EntityType::class, [
                'class'        => Category::class,
                'choice_label' => 'name',
                'expanded'     => false,
                'multiple'     => false,
            ])
            ->add('posterFile', VichImageType::class, [
                'required'       => false,
                'download_label' => new PropertyPath('poster'),
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Program::class,
        ]);
    }
}

src/Controller/ProgramController.php
<?php declare(strict_types=1);

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Program;
use App\Form\ProgramType;
use App\Repository\ProgramRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/program")
 */
class ProgramController extends AbstractController
{
    /**
     * @Route("/", name="program_index", methods={"GET"})
     */
    public function index(ProgramRepository $programRepository): Response
    {
        return $this->render('program/index.html.twig', [
            'programs' => $programRepository->findAllForIndex(),
        ]);
    }

    /**
     * @Route("/new", name="program_new", methods={"GET","POST"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function new(Request $request): Response
    {
        $program = new Program();
        $form = $this->createForm(ProgramType::class, $program);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($program);
            $entityManager->flush();

            return $this->redirectToRoute('program_index');
        }

        return $this->render('program/new.html.twig', [
            'program' => $program,
            'form'    => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="program_show", methods={"GET"}, requirements={"slug"="^[a-z0-9-]+$"})
     */
    public function show(Program $program): Response
    {
        return $this->render('program/show.html.twig', [
            'program' => $program,
        ]);
    }

    /**
     * Show all programs for one category.
     *
     * @Route("/category/{categorySlug}", name="program_by_category")
     */
    public function showProgramsByCategory(ProgramRepository $programRepository, ?string $categorySlug = null): Response
    {
        if (!$categorySlug) {
            throw $this->createNotFoundException('No categorySlug has been sent to find a category in category\'s table.');
        }
        $category = $this->getDoctrine()
            ->getRepository(Category::class)
            ->findOneBy(['slug' => $categorySlug]);
        if (!$category) {
            throw $this->createNotFoundException('No category with ' . $categorySlug . ' slug, found in category\'s table.');
        }

        $programs = $programRepository->findByCategories($category);

        return $this->render('program/index.html.twig', [
            'programs'     => $programs,
            'categoryName' => $category->getName(),
        ]);
    }

    /**
     * @Route("/{slug}/edit", name="program_edit", methods={"GET","POST"}, requirements={"slug"="^[a-z0-9-]+$"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function edit(Request $request, Program $program): Response
    {
        $form = $this->createForm(ProgramType::class, $program);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('program_index');
        }

        return $this->render('program/edit.html.twig', [
            'program' => $program,
            'form'    => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="program_delete", methods={"DELETE"}, requirements={"slug"="^[a-z0-9-]+$"})
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Program $program): Response
    {
        if ($this->isCsrfTokenValid('delete' . $program->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($program);
            $entityManager->flush();
        }

        return $this->redirectToRoute('program_index');
    }
}

templates/program/_delete_form.html.twig
<form method="post" action="{{ path('program_delete', {'slug': program.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ program.id) }}">
    {{ include('_btn/_btn_delete.html.twig') }}
</form>

templates/program/_form.html.twig
{{ form_start(form) }}

    {{ form_row(form.title, {'label': 'title'|trans|title}) }}
    {{ form_row(form.synopsis, {'label': 'synopsis'|trans|title}) }}
    {{ form_row(form.year, {'label': 'year'|trans|title}) }}
    {{ form_row(form.country, {'label': 'country'|trans|title}) }}
    {{ form_row(form.category, {'label': 'category'|trans|title}) }}
    {{ form_row(form.posterFile, {'label': 'image'|trans|title}) }}

    {{ form_rest(form) }}

    <button class="btn btn-primary">{{ button_label|default('save')}}</button>

{{ form_end(form) }}

templates/program/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'edit.program'|trans }}{% endblock %}

{% block main %}
    <div class="container">
        <div class="d-flex align-items-center">
            <div class="flex-grow-1">
                <h1 class="text-center ">{{ 'edit.program'|trans|capitalize }}</h1>
            </div>
            <div class="row d-flex align-items-center justify-content-end">
                <a class='btn btn-primary m-1'
                   href="{{ path('program_show', {'slug': program.slug}) }}">{{ 'back'|trans }}</a>
                {{ include('program/_delete_form.html.twig') }}
            </div>
        </div>
        {{ include('program/_form.html.twig', {'button_label': 'Update'|trans|capitalize}) }}
    </div>
{% endblock %}

templates/program/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Séries{% endblock %}

{% block main %}
    <h1 class="text-center">{% if categoryName is defined %} {{ categoryName | title }} catégorie {% else %} Séries {% endif %}</h1>
    <div class="container-fluid">

        <div class="card-deck">
            {% for programInfos in programs %}

                <div class="card bg-card">
                    <img class="card-img-top" alt="img {{ programInfos.program.title }}"
                         src="{{ programInfos.program.poster? vich_uploader_asset(programInfos.program, programInfos.program.posterFile) : asset('build/images/program/placeholder_program.jpg') }}">
                    <div class="card-body">
                        <h5 class="card-title"><a
                                    href="{{ path('program_show', {'slug': programInfos.program.slug}) }}">{{ programInfos.program.title }}</a>
                        </h5>
                        <p class="card-text">{{ programInfos.program.synopsis }}.</p>
                    </div>
                    <div class="card-footer">
                        <span class="badge badge-pill badge-primary">{{ programInfos.nbSeasons}} saisons</span>
                        <span class="badge badge-pill badge-primary">{{ programInfos.nbEpisodes }} episodes</span>
                        <span class="badge badge-pill badge-primary">{{ programInfos.nbActors | length }} acteurs</span>
                        <small class="text-muted float-right">maj: {{ programInfos.program.updatedAt | date("d/m/Y") }}</small>
                    </div>
                </div>
                <!-- Use modulo to add divs to handle break points -->
                {% set sm = loop.index % 1 %}
                {% set md = loop.index % 2 %}
                {% set lg = loop.index % 2 %}
                {% set xl = loop.index % 3 %}

                {% if sm == 0 %}
                    <div class="w-100 d-none d-sm-block d-md-none mt-4"></div>
                {% endif %}

                {% if md == 0 %}
                    <div class="w-100 d-none d-md-block d-lg-none mt-4"></div>
                {% endif %}

                {% if lg == 0 %}
                    <div class="w-100 d-none d-lg-block d-xl-none mt-4"></div>
                {% endif %}

                {% if xl == 0 %}
                    <div class="w-100 d-none d-xl-block mt-4"></div>
                {% endif %}

            {% else %}
                Desolé pas de série pour l'instant.
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/program/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'new.program'|trans }}{% endblock %}

{% block main %}
    <div class="container">
        <h1 class="text-center">{{ 'new.program'|trans|capitalize }}<span class="float-right">
                <a class='btn btn-primary m-1'
                   href="{{ path('program_index') }}">{{ 'back'|trans }}</a>
            </span></h1>

        {{ include('program/_form.html.twig', {'button_label': 'save'|trans|capitalize}) }}
    </div>
{% endblock %}

templates/program/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{ program.title }}{% endblock %}

{% block main %}
    <div class="container-fluid">
    <h1 class="mt-0 text-center">{{ program.title }}</h1>
    <div class="media media-bg">
       <img class="align-self-center mr-3" src="{{ program.poster? vich_uploader_asset(program, program.posterFile)
        : asset('build/images/program/placeholder_program.jpg')  }}" alt="{{ program.title }} poster">
        <div class="media-body pr-3">
            <h2> Synopsis : </h2>
            <p>{{ program.synopsis }}</p>
            <h2> Saisons : </h2>
            {% for season in program.seasons %}
                <div>
                    <h3><a href="{{ path('season_show', {programSlug: program.slug, number: season.number}) }}">Saison n°{{ season.number }}</a>
                        <span class="text-muted small">({{ season.episodes | length }} épisodes{{ season.year? ' - ' ~ season.year: ''}})</span>
                        </h3>
                    <p>{{ season.description?: 'pas de description pour l\'instant' }}</p>
                </div>
            {% else %}
                Pas de saison pour l'instant.
            {% endfor %}
            <h2> Acteurs : </h2>
            {% for actor in program.actors %}
                    <a href="{{ path('actor_show', {slug: actor.slug}) }}">{{ actor.displayName }}</a>{{ loop.last ? '.' : ',' }}

            {% else %}
                Aucun acteur trouvé.
            {% endfor %}
            <p>Catégorie : <a href="{{ path('program_by_category', {categorySlug: program.category.slug}) }}">{{ program.category.name }}</a> <span class="float-right">dernière maj:{{ program.updatedAt | date('d/m/Y') }}</span></p>
        </div>
    </div>
    </div>
{% endblock %}